name: wheather_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: 8.0.1
  flutter_bloc: 8.0.0
  intl: 0.17.0
  auto_route: 3.2.0
  json_serializable: 6.1.1
  provider: 6.0.1
  fimber_io: 0.6.4
  get_it: 7.2.0
  dio: 4.0.1
  permission_handler: 9.2.0
  flutter_secure_storage: 5.0.2
  flutter_device_type: 0.4.0
  flutter_screenutil: 5.0.3
  flutter_svg: 0.23.0+1
  injectable: 1.5.0
  collection: 1.15.0
  freezed: 1.1.0
  equatable: 2.0.3
  retrofit: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  bloc_test: 9.0.1
  mockito: 5.0.17
  auto_route_generator: 3.2.0
  injectable_generator: 1.5.2
  retrofit_generator: 3.0.0+2
  build_runner: 2.1.5

flutter:
  uses-material-design: true
  assets:
  - assets/images/svg/icons/
 
flutter_intl:
  enabled: true
  class_name: Strings